replicaCount: 1
dns_resolver:
  enabled: false
service:
  name: ssh-tunnel
image:
  repository: kroniak/ssh-client
  tag: latest
services:
  sish:
    domain: sish.example.com
    port: 22222
    request:
      domain: example
      port: 80
    from:
      domain: exampleservice
      port: 80