apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loadbalancer.fullname" . }}-conf
  labels:
    {{- include "loadbalancer.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "nginx/*").AsConfig | indent 2 }}